### ISSUE TITLE
Move all methods to a `src` folder

### ISSUE THREAD

**Issue by WaldoJeffers** [WaldoJeffers/conductor#1]
Title says it all 👍 Beware of import paths in the `__tests__` folder

**Comment by ganes1410** [comment]
hi,can i do this?

**Comment by WaldoJeffers** [comment]
@ganes1410 Sure, your help is more than welcome 😄

**Comment by WaldoJeffers** [comment]
Closed in https://github.com/WaldoJeffers/conductor/pull/6
