### ISSUE TITLE
Add a flatten method

### ISSUE THREAD

**Issue by Haegin** [WaldoJeffers/conductor#23]
Currently there's no way to flatten a nested list such as `[1, 2, [3, 4, [5, 6], [7, 8]]]` into `[1, 2, 3, 4, 5, 6 , 7, 8]`.

**Comment by WaldoJeffers** [comment]
@Haegin Excellent suggestion, I'll start working on it this week end

**Comment by WaldoJeffers** [comment]
Done in https://github.com/WaldoJeffers/conductor/commit/d751061f40136bc8f84ffd9c67fd4554543f797c

**Comment by Haegin** [comment]
Great, thanks! I noticed that the docs for flatten seem to be in the guides section though, is that deliberate?

**Comment by WaldoJeffers** [comment]
Fixed in https://github.com/WaldoJeffers/conductor/commit/6bb11e700e61d86fac7ad5a451e92d47f3a072c4 ^^

**Comment by WaldoJeffers** [comment]
I was unsure about what to do for objects, there seems to be a consensus on the following:
```javascript
flatten({ a: {b : 1}}) // { 'a.b' : 1}
```

See https://github.com/hughsk/flat for reference

Other solutions:
`flatten({ a: {b : 1}}) // { b : 1}`

`flatten({ a: {b : 1}}) // { a: 1, b : 1}`

What do you think @Haegin ?

**Comment by Haegin** [comment]
I'm not sure I've ever used `flatten` on an object, so I'd be tempted to only define it for arrays. If someone has a convincing use case for `flatten`ing an object, I'm sure they'll open an issue to request it, and then you'll have an end user to drive the design.

**Comment by WaldoJeffers** [comment]
Will leave it as it is for now, I prefer having methods which work on all collection types. This will be released in v1.1.0
