### ISSUE TITLE
Add an every method

### ISSUE THREAD

**Issue by WaldoJeffers** [WaldoJeffers/conductor#25]
**Checklist**
- [x] It should work on `Arrays, Sets, Objects, Maps`
- [x] Use it in `equals` source, and replace `Array.prototype.every` where necessary
- [x] Document it

**Comment by alextoudic** [comment]
Fixed in [#30](https://github.com/WaldoJeffers/conductor/pull/30)

**Comment by alextoudic** [comment]
Fixed in #30

**Comment by WaldoJeffers** [comment]
Nice work, closing 💪
